### ISSUE TITLE
failing to generate c3 directive based charts dynamically

### ISSUE THREAD

**Issue by madasuk** [wasilak/angular-c3-simple#1]
Thanks for very nice c3 chart directive. But I am facing a problem when trying compile the c3 directives dynamically. Please see my post http://stackoverflow.com/questions/28188479/angularjs-failing-to-generate-c3-directive-based-charts-dynamically. Could you please help me to fix it?

I am trying to do some thing like that is shown at http://plnkr.co/edit/0XtT0f?p=preview

**Comment by wasilak** [comment]
Hi,
I have answered your ques­tion on Stack­Over­flow and here is fixed [Plnkr](http://plnkr.co/edit/wiiUMk2KoHHrK4D1HdNu?p=preview).
Hope it helps :)

**Comment by madasuk** [comment]
Thanks alot.
