### ISSUE TITLE
Axis outputs as a thick line

### ISSUE THREAD

**Issue by pyros-endgame** [wasilak/angular-c3-simple#15]
So I haven't debugged this to any crazy extent yet so the issue might be c3.js related or it might be related to this directive. Basically the x and y axis work fine but they end up being a large thick line which I am not sure is the intention.

![image](https://cloud.githubusercontent.com/assets/11553732/20580979/a7ecb24e-b18a-11e6-81f8-9aefec5746f8.png)

As you can see (I have the y axis bar removed for styling purposes) the axis is a large thick black line and I'm not sure how its getting its computation to set it to that thickness

**Comment by wasilak** [comment]
Honestly, no idea :) I've never seen this. Does in happen when you use c3.js without directive? Maybe some kind of CSS is messing this up?
