### ISSUE TITLE
facing problem with c3 chart directives data reload and transform chart type

### ISSUE THREAD

**Issue by madasuk** [wasilak/angular-c3-simple#2]
Hi Wasilak, from the example you have given on Github to tranform the chart type, I am trying to change the chart display type but some I am failing to do it and also reloading of the data using c3 directives. Could you please help me please to fix this. Please see my post at http://stackoverflow.com/questions/28191802/angulrjs-need-to-help-to-make-c3-direectives-to-reload-data-and-changing-chart.
And you can refer my plunker at http://plnkr.co/edit/wWJx3zU3Sm1cN9ZCtvoh?p=preview.

Thanks in advance.

**Comment by wasilak** [comment]
Hi again. Check out my answer on [StackOverflow](http://stackoverflow.com/questions/28191802/angulrjs-need-to-help-to-make-c3-direectives-to-reload-data-and-changing-chart)

**Comment by madasuk** [comment]
Perfect. Thanks a lot for nice directives. It simplified our life. By the way side question, do you have any plans to release directives for another powerful library d3plus (http://d3plus.org/)
