### ISSUE TITLE
need title support for the charts 

### ISSUE THREAD

**Issue by madasuk** [wasilak/angular-c3-simple#3]
Hi, Is it possible to add title for the charts in your directives?

**Comment by wasilak** [comment]
Hi, What exactly do you mean by _title_? In C3.js charts, as far as I know, title is not a part of chart, so you have to handle it yourself outside of chart canvas. It can be any HTML outside of it, but I have no clue how to insert it directly into canvas, if that's what you intend to do.

**Comment by madasuk** [comment]
Yes, that is what I am looking to insert the title directly into the canvas. But from your explanation I feel that feature can't be expected from c3 charts itself.  I have come across donut: {  title: 'Title'} at http://c3js.org/reference.html for donut chart title and thought may be there would be some possibility to insert title for other charts too. If this feature is not a simple one, you can close the ticket. Thanks.

**Comment by wasilak** [comment]
Sorry for late answer. Right now I don't see direct possibility to render title on any os C3 charts besides donut you mentioned. I guess for now you'll have to go around it. If it will be supported by C3, then my Angular directive will automatically support it as an chart config option.
