### ISSUE TITLE
data as json require an empty columns array

### ISSUE THREAD

**Issue by ghost** [wasilak/angular-c3-simple#4]
Hello,

Here is a chart option that work with C3 but does not work with c3-simple :

data: {
    json: [{date: '2015-07-10 20:10:00', consumption: 1}],
    keys: {value: ['consumption']},
    type: 'bar'
}

To work with c3-simple, we must add a empty columns, like that (it took me an hour to find...):

data: {
    columns:[],
    json: [{date: '2015-07-10 20:10:00', consumption: 1}],
    keys: {value: ['consumption']},
    type: 'bar'
}

Thanks for the nice lib c3-simple, have a nice day !

**Comment by wasilak** [comment]
Hi,

Thanks for pointing that out. C3 probably probably uses `columns: []` as a default but somewhere in process **angular-c3-simple** does not set this default. I'll look into this issue.

Thanks!
Peter

**Comment by wasilak** [comment]
Hi @Foonkyz,

Sorry it took so long, but I've finally found few minutes today and hopefully fixed issue you found. Now you should be able to pass any `data` definition which C3.js accepts. Check out version `0.0.7`.

Hope it works! :)

**Comment by ghost** [comment]
Thanks a lot.

Le jeudi 6 août 2015, Piotr Wasilewski notifications@github.com a écrit :

> Hi @Foonkyz https://github.com/Foonkyz,
> 
> Sorry it took so long, but I've finally found few minutes today and
> hopefully fixed issue you found. Now you should be able to pass any data
> definition which C3.js accepts. Check out version 0.0.7.
> 
> Hope it works! :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wasilak/angular-c3-simple/issues/4#issuecomment-128477461
> .

## 

Stéphane Ravet

09.50.98.10.54
06.95.84.91.43
