### ISSUE TITLE
Data refresh transition

### ISSUE THREAD

**Issue by MattiJarvinen** [wasilak/angular-c3-simple#6]
You could probably use chart.load to refresh data columns like I did in plnkr below. That would also allow transition animations.

http://plnkr.co/edit/2z9Quc94vTBGDelftlLx?p=preview

Thanks, for your simple and not overly complex solution. Especially using a service for passing javascript API was something I haven't seen before and will use that some day.

**Comment by gurix** [comment]
:+1: Looks great, thanks. I used your implementation that looks much cleaner.

**Comment by wasilak** [comment]
Hi, I have added data update watching, so it will be handled (and animated) properly. Check out version `0.0.8` (particularly commit: 5259b19ab805a0895f110f795c28e497356b169e).
