### ISSUE TITLE
c3SimpleService + ng-if

### ISSUE THREAD

**Issue by dinizime** [wasilak/angular-c3-simple#8]
Iam using the c3-simple directive inside a div with ng-if and that causes the c3SimpleService to come empty. There is any work arround to refresh the information on c3SimpleService?

**Comment by wasilak** [comment]
Hi @dinizime ,

Are you able to provide more in detail example, maybe using service like https://jsfiddle.net/ or http://codepen.io/ ?

I would gladly look into this.

**Comment by wasilak** [comment]
Hi again,

I tried to reproduce that. In both cases it worked, see below.
1. `div` with `ng-if` toggled by button: 

``` html
<button type="button" name="button" ng-model="toggle" ng-click="toggle = (toggle == 1 ) ? 0 : 1">toggle chart</button>
  <div ng-if="toggle == 1">
    <c3-simple id="chart" config="chart"></c3-simple>
  </div>
```
1. `ng-if` directly on `c3-simple` directive toggled by button: 

``` html
<button type="button" name="button" ng-model="toggle" ng-click="toggle = (toggle == 1 ) ? 0 : 1">toggle chart</button>
  <c3-simple ng-if="toggle == 1" id="chart" config="chart"></c3-simple>
```

![chart_ngif](https://cloud.githubusercontent.com/assets/436730/15799767/7eb0288e-2a67-11e6-8ee2-3456dd99cd47.gif)

**Comment by wasilak** [comment]
As I can't reproduce it and code itself had undergone some rewriting so this issue shouldn't occur.
